### ISSUE TITLE
縮圖預覽問題

### ISSUE THREAD

**Issue by lilansier** [kokorolove/comic-manager#1]
在匯入之後沒有出現縮圖
請問可能哪邊有錯
需要提供什麼檔案
[config 文字檔.txt](https://github.com/kokorolove/comic-manager/files/2343618/config.txt)

![image](https://user-images.githubusercontent.com/38000721/44959019-ee7d4e00-af1a-11e8-94f9-1a696cdc9a4b.png)

**Comment by lilansier** [comment]
![image](https://user-images.githubusercontent.com/38000721/44959434-b11bbf00-af20-11e8-8b82-def91e0a14ff.png)

**Comment by kokorolove** [comment]
沒有出現縮圖的原因我猜有兩個：
  -  資料夾內沒有壓縮檔。這個軟體是用來管理壓縮檔的，所以資料夾內的圖片會被無視。如果你的檔案都已經解壓了，用其他島民推薦的軟體來瀏覽會比較合適，例如 MangaMeeya，Xnview，FastStone 等。
  - 若是連壓縮檔的縮圖都沒出現的話，可能是你的 config.xml 未使用 unicode 儲存。你給的 config.xml 我開起來是亂碼，有可能你用的文字編輯器不支援 unicode，所以把中文路徑存成了亂碼。

第二個錯誤視窗和縮圖無關，只要在程式開啟的情況下修改 config.xml，關閉程式時就會跳出這個錯誤。我在下次更新時會處理這個問題，感謝您的回報。

**Comment by lilansier** [comment]
好的
感謝您的解答
祝你一切順利
