### ISSUE TITLE
參與開發

### ISSUE THREAD

**Issue by dksjlhkjdh** [kokorolove/comic-manager#3]
你好

你開發的這套 manager 我覺得功能相當完備，不知是否可以參與開發？
身為開發者，想做的 feature 或 customize 的地方可能比較多，不如自己跳進來做。

感謝

**Comment by kokorolove** [comment]
您好，感謝您的探詢~ 
在談合作之前，想先了解一下您所擅長的開發工具和語言 (←這點很重要)
以及您大概是想加入怎麼樣的 feature 呢 ? 謝謝~

**Comment by dksjlhkjdh** [comment]
你好

跟 winform 相關的話，我目前最擅長的是 python with pyQt，也曾寫過 C# winform, C++ with Qt 等。
我想加的 feature 應該還有
1. 刪除檔案 (可能會下載到重複的)。
2. 改善 file tag，直接在檔名加工感覺很奇怪，而且還會加錯地方 (加到開頭) 導致檔名 parsing 錯誤，改用 DB 可能是比較好的解法，當然如此會增加 dependancy，也許可以選擇改善原本的 meta data 就好，可以再討論啦。
3. 對壓縮檔內容做編輯，如果載到漢化本，漢化組的頁面我並不想留，想直接砍掉。
4. 搜尋改善，目前只能 full string matching, 第一是看能不能支援一定程度的 wildcard，不然直接支援 re；第二是目前 tag 加在檔名，所以搜 file tag 等於搜檔名，如果 2. 項功能改善的話，勢必要重做搜尋的部份。

目前看到就這些，如不願對上述更動的話，也希望能讓我 clone 一份，能做到如此程度的完善功能，想必也花了很多時間，不 share 出來果然還是太可惜了。

如果是擔心身份的問題，也可以直接在此帳號開個 public repository 即可。

感謝

**Comment by kokorolove** [comment]
您好，感謝您的提案。
1. 刪檔：當初沒放入刪除功能是為了避免造成不可逆的錯誤，不過我可以增加搬到資源回收桶的功能。
2. 編輯壓縮檔內容：目前程式是使用 [SharpCompress](https://github.com/adamhathcock/sharpcompress) 這個類別庫處理壓縮檔，該類別庫不支援 RAR 和 7Zip 等常見格式的寫入，因此技術上可能無法實現這個要求。不過我可以在縮圖的預覽視窗加一個按鈕，方便使用者開啟預設的程式來編輯壓縮檔 (目前點右鍵 -> Open -> Open in shell 也可達到這個目的，就是麻煩了點)。
3. C# 的檔案庫可以直接支援用 Regex 搜尋檔名，當初沒啟用 Regex 是因為它和 incremental search 相衝，而我覺得後者比較實用就捨去前者。不過也是可以加上一個 checkbox 讓使用者在兩者之間選擇。
4. 標籤加到開頭導致檔名 parsing 錯誤：我可以在標籤的編輯視窗增加一個 Add tag 按鈕來避免這個
問題，如下圖所示：
<center><img src="https://user-images.githubusercontent.com/42807610/47758647-d2d8be80-dca3-11e8-8588-dc48ae4f8718.png" style="width:80%;margin:auto;"/></center>

5. 關於資料庫：使用資料庫管理檔案必須付出很高的效能成本，相較於直接存取檔案系統的優勢有待商榷。另外，標籤存放在檔名即使用檔案總管也可輕鬆搜尋，一旦寫入資料庫後就只有特定程式才能存取了，這對使用者來說也未必是好事，可能還是要有更強烈的誘因我才會考慮用資料庫吧
6. 以上 1-4 點的功能實現起來不難，我在這個周末可以完成。
7. 這個專案的代碼目前尚未打算開源，若您能實現我想做卻做不到或沒時間做的功能，我會將您的 github 帳號加入一個 private repository 讓您在上面工作。您所做的貢獻會被列在這個專案的主頁面。

**Comment by dksjlhkjdh** [comment]
你好

感謝你願意為這些需求做修改，我會說想要參與是因為在無償的前提下，多數情況開發者都懶得為別人的需求而做開發，所以才想乾脆自己來做。
如果您願意做當然是最好XD，在此先感謝你的付出！
